[package]
name = "sdk_noise"
version = "0.0.1"
authors = ["Adrian <adrian.eddy@gmail.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
exaecut-after-effects = { path = "../../after-effects" }
rayon = "1.12"

[build-dependencies]
exaecut-pipl = { path = "../../pipl" }
